spring.application.name=population

# Configuration BDD Render PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-da34c3ou01pc73fs3nh0-a.frankfurt-postgres.render.com:5432/population_db_68
spring.datasource.username=dreghost
spring.datasource.password=CTXY81D1e133Gl4yMspNAE4cvoI4EyA0

# Driver PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true